---
version: '3.3'
services:
  api:
    image: ietf/at:v0.3.0
    container_name: api
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: unless-stopped
  ui:
    image: ietf/at-ui:v0.3.0
    container_name: ui
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: unless-stopped
  proxy:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./at.env
    depends_on:
      - api
      - ui
    links:
      - api
      - ui
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx-templates:/etc/nginx/templates/

volumes:
  nginx_secrets:
