---
version: '3.3'
services:
  api:
    build: ietf-at/.
    container_name: api
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    restart: "unless-stopped"
  ui:
    build: ietf-at-ui/.
    container_name: ui
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: "unless-stopped"
  proxy:
    build: .
    depends_on:
      - api
      - ui
    links:
      - api
      - ui
    ports:
      - '80:80'
      - '443:443'
    restart: "unless-stopped"
