---
version: '3.3'
services:
  api:
    build: ietf-at/.
    container_name: api
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: "unless-stopped"
  ui:
    build: ietf-at-ui/.
    container_name: ui
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://ietfa.amsl.com:514"
    restart: "unless-stopped"
  proxy:
    build: .
    depends_on:
      - api
      - ui
    links:
      - api
      - ui
    ports:
      - '80:80'
      - '443:443'
    restart: "unless-stopped"
